// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUn_2x5cJnpO65y9mJIvas3lJ4SsnHPXg',
    appId: '1:628462975918:web:7fd774c1e3b4ef39c9663f',
    messagingSenderId: '628462975918',
    projectId: 'taxiusa-atlanta',
    authDomain: 'taxiusa-atlanta.firebaseapp.com',
    storageBucket: 'taxiusa-atlanta.firebasestorage.app',
    measurementId: 'G-1Y3KXHK7T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7mUbWB1NVSa_HLOM2f1rvc_h8p-Vsoyk',
    appId: '1:628462975918:android:acc6704f63433549c9663f',
    messagingSenderId: '628462975918',
    projectId: 'taxiusa-atlanta',
    storageBucket: 'taxiusa-atlanta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAInIINb90pZrvdLvdUL9Skkfe6lTb3Ytc',
    appId: '1:628462975918:ios:b4b001ac53c60322c9663f',
    messagingSenderId: '628462975918',
    projectId: 'taxiusa-atlanta',
    storageBucket: 'taxiusa-atlanta.firebasestorage.app',
    iosBundleId: 'com.example.evasTaxiDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAInIINb90pZrvdLvdUL9Skkfe6lTb3Ytc',
    appId: '1:628462975918:ios:b4b001ac53c60322c9663f',
    messagingSenderId: '628462975918',
    projectId: 'taxiusa-atlanta',
    storageBucket: 'taxiusa-atlanta.firebasestorage.app',
    iosBundleId: 'com.example.evasTaxiDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUn_2x5cJnpO65y9mJIvas3lJ4SsnHPXg',
    appId: '1:628462975918:web:19f8ac716b6837d1c9663f',
    messagingSenderId: '628462975918',
    projectId: 'taxiusa-atlanta',
    authDomain: 'taxiusa-atlanta.firebaseapp.com',
    storageBucket: 'taxiusa-atlanta.firebasestorage.app',
    measurementId: 'G-Q183DY4571',
  );
}
